version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/demand-capacity-mgmt-backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/demand-capacity-mgmt-specification"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/demand-capacity-mgmt-frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5