/*
 * ******************************************************************************
 * Copyright (c) 2023 BMW AG
 * Copyright (c) 2023 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * *******************************************************************************
 */

SET search_path TO public;

CREATE TABLE IF NOT EXISTS admin_ruleset
(
    id         INT GENERATED BY DEFAULT AS IDENTITY primary key,
    percentage int,
    enabled    bool
);

INSERT INTO admin_ruleset (percentage, enabled)
VALUES (5, false),
       (10, false),
       (15, false),
       (20, false),
       (25, true),
       (30, false),
       (35, false),
       (40, false),
       (45, false),
       (50, true),
       (55, false),
       (60, false),
       (65, false),
       (70, false),
       (75, true),
       (80, false),
       (85, false),
       (90, false),
       (95, false),
       (100, true);